export const filmsConstants = {

    API: '/titles',

    FETCH_ALL_PROCESSING: 'FETCH_FILMS_PROCESSING',
    FETCH_ALL_SUCCESS: 'FETCH_FILMS_SUCCESS',
    FETCH_ALL_ERROR: 'FETCH_FILMS_ERROR',

    PROCESSING: 'FETCH_FILM_PROCESSING',
    SUCCESS: 'FETCH_FILM_SUCCESS',
    ERROR: 'FETCH_FILM_ERROR',

    UPDATE_PROCESSING: 'UPDATE_FILM_PROCESSING',
    UPDATE_SUCCESS: 'UPDATE_FILM_SUCCESS',
    UPDATE_ERROR: 'UPDATE_FILM_ERROR',

    DELETE_PROCESSING: 'DELETE_FILM_PROCESSING',
    DELETE_SUCCESS: 'DELETE_FILM_SUCCESS',
    DELETE_ERROR: 'DELETE_FILM_ERROR',

    CREATE_PROCESSING: 'CREATE_FILM_PROCESSING',
    CREATE_SUCCESS: 'CREATE_FILM_SUCCESS',
    CREATE_ERROR: 'CREATE_FILM_ERROR',

    RESET_DATA: 'RESET_FILM_DATA'

}